### ISSUE TITLE
Closing spider before empty queue

### ISSUE THREAD

**Issue by alafanechere** [mbriliauskas/scrapy-rabbitmq-link#2]
Hi Mantas,
I am trying to implement a middleware that closes my spider if some condition is met.
My problem is that the spider does not close when I raise a `scrapy.exception.CloseSpider` exception. As far as I understand the scheduler behaviour requests are sent to spider until the Rabbit MQ queue is empty.

Do you have any advice on how I could stop enqueing urls to the engine  and close the spider properly ?

**Comment by mbriliauskas** [comment]
Good day Augustin,

it depends, whether you want to stop the spider immediately, or wait until current requests bunch will finish execution. In both cases there are solutions, [here](http://stackoverflow.com/questions/9699049/how-do-i-stop-all-spiders-and-the-engine-immediately-after-a-condition-in-a-pipe) is a very nice post from stackoverflow discussing this topic.

Hope that helps.

**Comment by alafanechere** [comment]
Thanks for this great ressource. Sorry because this is not related to your package. I did not know I could not call Close Spider outside the spider's code... I called `spider.crawler.engine.close_spider(spider)`. Now I am try to figure out how to get the enqueued request to requeue them in the Rabbit MQ queue.

**Comment by mbriliauskas** [comment]
To requeue item to Rabbit MQ you need to ack the message with flag requeue=True, and by default it will be put back to same queue and same position it was before the receiving. If you want to requeue message to end of the queue you first need first to ack the message with requeue=False flag and then publish it to same queue.

Other usable option is to create [DLX queue](https://www.rabbitmq.com/dlx.html) where you can send unprocessed messages with nack requeue=False. If your original queue is DLX routed, by just nacking you will requeue your message to queue.

Hope that helps.
